spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://atufa.database.windows.net:1433;database=atufa;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: atufa
    password: '!stCutd@ne12'
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
