debug: true
server:
  port: 3000
spring:
  datasource:
    url: jdbc:sqlserver://atufa.database.windows.net:1433;database=atufa;user=atufa@atufa;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: atufa
    password: !stCutd@ne12
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
